name: dev

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup tools
        run: |
          python -m pip install --upgrade pip
          pip install docker-compose

      - name: Check spelling
        uses: crate-ci/typos@master

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Run Perl::Critic
        uses: natanlao/perl-critic-action@v1.1

      - name: Validate docker-compose.yml
        run: docker-compose config

  docker:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DHUB_USERNAME }}
          password: ${{ secrets.DHUB_TOKEN }}

      - name: login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: get commit sha
        run: |
          curl --silent --fail --fail-early $GITHUB_API_URL/repos/vergoh/vnstat/commits/master | \
            jq -r .sha | \
            sed -e 's:^:latest_commit=:g' >> $GITHUB_ENV

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-dev
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            vergoh/vnstat:dev
            ghcr.io/${{ github.repository_owner }}/vnstat:dev
          labels: |
            org.opencontainers.image.version=${{ env.latest_commit }}

      - name: image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
