name: lint
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Setup tools
        run: |
          python -m pip install --upgrade pip
          pip install docker-compose

      - name: Check spelling
        uses: crate-ci/typos@master

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Validate docker-compose.yml
        run: docker-compose config
