name: lint
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check spelling
        uses: crate-ci/typos@master

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Run Perl::Critic
        uses: natanlao/perl-critic-action@v1.1

      - name: Show docker-compose (v1) version
        run: docker-compose version

      - name: Show docker compose (v2) version
        run: docker compose version

      - name: Validate docker-compose.yml (v1)
        run: docker-compose -f docker-compose.yml config

      - name: Validate docker-compose_isolated_httpd.yml (v1)
        run: docker-compose -f docker-compose_isolated_httpd.yml config

      - name: Validate docker-compose.yml (v2)
        run: docker compose -f docker-compose.yml config

      - name: Validate docker-compose_isolated_httpd.yml (v2)
        run: docker compose -f docker-compose_isolated_httpd.yml config
