name: CI

on:
  push:
    branches:
      - 'master'
  schedule:
    # one scheduled build on the first day of every month at 3:42
    - cron: '42 3 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DHUB_USERNAME }}
          password: ${{ secrets.DHUB_TOKEN }}

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: vergoh/vnstat:latest

      - name: image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
